website/riget/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views


from . import views

app_name = 'riget'
urlpatterns = [
    url(r'^$', auth_views.login, name='login'),
#    url(r'^$', views.loginView.as_view(), name='login'),
    url(r'out/$', auth_views.logout, name ='logout'),
    url(r'home/$', views.homeView.as_view(), name='home'),
    url(r'fet/$', views.fetView.as_view(), name='fet'),
    url(r'fet/nyrecord/$',views.nyfetrecordView.as_view(), name='nyfetrecord'),
    url(r'fet/nyperson/$',views.nyfetpersonView.as_view(), name='nyfetperson'),
    url(r'pib/$', views.pibView.as_view(), name='pib'),
    url(r'viewpatient/(?P<CPR>\d+)/$', views.fetpatientView.as_view(), name='fetview'),
    url(r'fet/change/(?P<CPR>\d+)/$', views.changefetpatientView.as_view(), name='fetchang'),
    url(r'fet/rchange/(?P<CPR>\d+)/$', views.nyfetrecordView.as_view(), name='fetrchange'),
]

website/website/urls.py
from django.conf.urls    import url, include
from django.contrib      import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('riget.urls')),
]

website/riget/forms.py
from django import forms

class nyFetPerson(forms.Form):
	firstname = forms.CharField(label="fornavn")
	lastname = forms.CharField(label="lastname")
	CPR = forms.CharField(label="CPR")
	FDG = forms.BooleanField(label="FDG", required=False)
	avastin = forms.BooleanField(label="avastin", required=False)
		

website/riget/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http      import HttpResponse
from django.views     import generic
from django.contrib   import messages
from django.template  import RequestContext
from django.conf      import settings
from django           import forms
from django.views.generic.edit  import CreateView, UpdateView, DeleteView
from django.core.urlresolvers   import reverse
from django.contrib.auth.models import User
from django.contrib.auth.forms  import AuthenticationForm
from .models import Fetrecords, Fetpersons
from .forms   import nyFetPerson
from django.db import connection


class loginView(generic.TemplateView):
	tamplate_name = 'registration/login.html'
	tamplate_name_in = 'riget/home.html'

	def get(self, request):
		form = AuthenticationForm(request)
		return render(request, self.tamplate_name, { 'form': form })

#	def post(self, request):
#		return render(request, self.tamplate_name_in, {})

class logoutView(generic.TemplateView):
	tamplate_name = 'riget/base.html'

	def get(self, request):
		return render(request, self.tamplate_name, {})

class homeView(generic.TemplateView):
	tamplate_name = 'riget/home.html'

	def get(self, request):
		return render(request, self.tamplate_name, {})

	def post(self, request):
		return render(request, self.tamplate_name, {})

class fetView(generic.TemplateView):

	tamplate_name = 'riget/fet.html'
	model_0 = Fetrecords
	model_1 = Fetpersons

	def get(self, request):

		if not request.user.is_authenticated():
			return redirect('/')
		cursor = connection.cursor()

		this = Fetrecords.objects.raw('SELECT riget_Fetrecords.*, riget_Fetpersons.firstname, riget_Fetpersons.lastname FROM riget_Fetrecords LEFT JOIN riget_Fetpersons ON riget_Fetpersons.CPR = riget_Fetrecords.CPR')
		print this
		list_r = len(Fetrecords.objects.all())
		list_p = len(Fetpersons.objects.all())

		#fields = ['CPR', 'age', 'scandate', 'scanner', 'tumor_type', 'roi_t_mean_b', 'roi_t_max_b', 'roi_tumor_vol', 'indikation_projekt', 'filter_t', 'MR_DCE']

		return render(request, self.tamplate_name, { 'fetlist':this, 'list_r':list_r, 'list_p':list_p })

		
	
	def post(self, request):
		return render(request, self.tamplate_name, {})

class fetpatientView(generic.TemplateView):
	tamplate_name = 'riget/fetpatient.html'

	def get(self, request, CPR):

		i_person = Fetpersons.objects.raw('SELECT riget_Fetpersons.* FROM riget_Fetpersons WHERE riget_Fetpersons.CPR = "' + str(CPR) + '";')
		i_record = Fetrecords.objects.raw('SELECT riget_Fetrecords.id, riget_Fetrecords.scandato, riget_Fetrecords.age, riget_Fetrecords.scanner, riget_Fetrecords.scantype_type, riget_Fetrecords.tumor_type, riget_Fetrecords.kurveform, riget_Fetrecords.roi_t_mean_b, riget_Fetrecords.roi_t_max_b, riget_Fetrecords.roi_tumor_vol, riget_Fetrecords.indikation_projekt, riget_Fetrecords.interessant_case FROM riget_Fetrecords WHERE riget_Fetrecords.cpr = "' + str(CPR) + '";')
		return render(request, self.tamplate_name, { 'person':i_person, 'records':i_record })

	def post(self, request):
		return render(request, self.tamplate_name, {})


class nyfetrecordView(generic.TemplateView):
	tamplate_name = 'riget/nyfetrecord.html'
	model = Fetrecords

	def get(self, request):
		return render(request, self.tamplate_name, {})

	def post(self, request):
		if request.mothod == "POST":
			form = nyFetRecord(request.POST)

			i_person = Fetpersons.objects.raw('SELECT riget_Fetpersons.id, riget_Fetpersons.firstname, riget_Fetpersons.lastname FROM riget_Fetpersons WHERE riget_Fetpersons.cpr = "' + request.POST['cpr'] + '";')

			u_record = Fetrecords(cpr = request.POST['cpr'],
				firstname = i_person.firstname,
				lastname = i_person.lastname,
				age = request.POST['alder'],
				scandato = request.POST['dato'],
				scanner = request.POST['scanner'],
				scantype_type = request.POST['scan_type'],
				filter_t = request.POST['filter'],
				scantype_pct = request.POST['pct'],
				MR_DCE = request.POST['MR_DCE'],
				MR_DSC = request.POST['MR_DSC'],
				tumor_type = request.POST['tumor_type'],
				kurveform = request.POST['kurveform'],
				indikation_uafklaret_process = request.POST['indikation_uafklaret_process'],
				indikation_gradering = request.POST['indikation_gradering'],
				indikation_biopsioptimering = request.POST['indikation_biopsioptimering'],
				indikation_epi_kir = request.POST['indikation_epi_kir'],
				indikation_praeoperativ_planlaegning = request.POST['indikation_praeoperativ_planlaegning'],
				indikation_rt_planlaegning = request.POST['indikation_rt_planlaegning'],
				indikation_malign_transformation = request.POST['indikation_malign_transformation'],
				indikation_recidiv_straalefoelger = request.POST['indikation_recidiv_straalefoelger'],
				indikation_monitorering = request.POST['indikation_monitorering'],
				indikation_tidlig_postop_vurdering = request.POST['indikation_tidlig_postop_vurdering'],
				indikation_pseudo_progression = request.POST['indikation_pseudo_progression'],
				indikation_projekt = request.POST['indikation_projekt'],
				indikation_andet = request.POST['indikation_andet'],
				roi_b_avg = request.POST['roi_b_avg'],
				roi_suv_threshold = request.POST['roi_suv_threshold'],
				roi_suv_mean = request.POST['roi_suv_threshold'],
				roi_t_mean_b = request.POST['roi_t_mean_b'],
				roi_suv_max = request.POST['roi_suv_max'],
				roi_t_max_b = request.POST['roi_t_max_b'],
				roi_tumor_vol = request.POST['roi_tumor_vol'],
				mr_t1_kontrastop = request.POST['mr_t1_kontrastop'],
				uni_multi_fokal = request.POST['uni_multi_fokal'],
				konklusion_followup = request.POST['konklusion_followup'],
				kbg_ml = request.POST['kbg_ml'],
				interessant_case = request.POST['interessant_case'])

		return render(request, self.tamplate_name, { 'form':form })

class nyfetpersonView(generic.TemplateView):
	tamplate_name = 'riget/nyfetperson.html'
	model = Fetpersons
	fields = ['firstname', 'lastname', 'CPR', 'FDG', 'avastin']

	def get(self, request):
		return render(request, self.tamplate_name, {})

	def post(self, request):
		if request.method == "POST":
			form = nyFetPerson(request.POST)

			u_firstname = request.POST['firstname']
			u_lastname = request.POST['lastname']
			u_CPR = request.POST['CPR']
			u_fdg = request.POST['FDG']
			u_avastin = request.POST['avastin']

			u_person = Fetpersons(CPR = u_CPR,
				firstname = u_firstname,
				lastname = u_lastname,
				FDG = u_fdg,
				avastin = u_avastin,
				lasrChangedBy = "admin")

			u_person.save()

		messages.success(request, "New FET patient oprettet succesfuldt")
		done = "SuccesFuldt oprettet " + str(u_firstname)
		return render(request, self.tamplate_name, { 'form':form, 'done':done }, RequestContext(request))



		return render(request, self.tamplate_name, {})


class changefetpatientView(generic.TemplateView):
	tamplate_name = 'riget/nyfetpersonchange.html'
	model = Fetpersons
	fields = ['firstname', 'lastname', 'CPR', 'FDG', 'avastin']

	def get(self, request, CPR):
		
		i_person = Fetpersons.objects.raw('SELECT riget_Fetpersons.* FROM riget_Fetpersons WHERE riget_Fetpersons.CPR = "' + str(CPR) + '";')
		return render(request, self.tamplate_name, { 'person':i_person })

	def post(self, request, CPR):
		if request.method == "POST":
			form = nyFetPerson(request.POST)

			u_firstname = request.POST['firstname']
			u_lastname = request.POST['lastname']
			u_CPR = request.POST['CPR']
			u_fdg = request.POST['FDG']
			u_avastin = request.POST['avastin']

		i_person = Fetpersons.objects.raw('UPDATE riget_Fetpersons SET CPR="' + str(u_CPR) + '", firstname="' + str(u_firstname) + '", lastname="' + str(u_lastname) + ', FDG="' + str(u_fdg) + ', avastin="' + str(u_avastin) + ' WHERE CPR="' + str(CPR) + '";')

		#t_person.save()


		return render(request, self.tamplate_name, {})


class pibView(generic.TemplateView):
	tamplate_name = 'riget/pib.html'

	def get(self, request):
		return render(request, self.tamplate_name, {})	

























#class Createuser(request):
	
	#user = User.objects.create_user('username', 'firstname', 'lastname', 'password', 'email', 'role', )

website/riget/templates/riget/base.html
<!DOCTYPE html>

<html>
<head>
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'riget/style.css' %}" />
	<!--<link rel="stylesheet" href="http://www.w3schools.com/lib/w3.css"/>-->
	<link rel="stylesheet" type="text/javascript" href="{% static 'riget/jquery-3.2.1.js' %}" />
	<script type="text/javascript" src="{% static 'riget/jquery-3.2.1.js' %}"></script>
	<script type="text/javascript" src="http://code.jquery.com/ui/1.10.0/jquery-ui.js"></script>
	<script type="text/javascript" src="{% static 'riget/jquery.tablesorter.js' %}"></script>	

	{% block Header %}
	{% endblock %}


	<title> {% block title %} Stuff to do {% endblock %} </title>
</head>

<body>
	<div id="box">
		<div id="header">
			<img class="w3-light-blue" id="riget" src="{% static 'riget/img/riget.png' %}" width="100%" height="100%"/>
		</div>

		<div id="menu">
			<ul>
				<li>
					<a href="{% url 'riget:home' %}">Home</a>
				</li>
				{% block menu %}
				{% endblock %}
				<li>
				<a href="{% url 'logout' %}">Logout</a>
				</li>
			</ul>
		</div>

		<div id="content">
			{% block body %}
			{% endblock %}
		</div>
	</div>

</body>


</html>

website/riget/templates/riget/fet.html
{% extends 'riget/base.html' %}
{% load staticfiles %}

{% block Header %}

<script>
	var myTextExtraction = function(node) 
	{ 
    		// extract data from markup and return it 
    		return node.childNodes[0].innerHTML; 
	} 
	$(document).ready(function() {
			$("#usertable").tablesorter( {textExtraction: myTextExtraction} );
		}
	
	);

	var options = {
		valueNames: [ 'CPR', 'Name' ]
	};

	var userList = List('users', options);

</script>

{% endblock %}


{% block title %}FET Oversigt{% endblock %}



{% block menu%}
	<li>
		<a href="{% url 'riget:nyfetrecord' %}">Ny Record</a>
	</li>
	<li>
		<a href="{% url 'riget:fet' %}">Oversigt</a>
	</li>
	<li>
		<a href="{% url 'riget:nyfetperson' %}">Ny Patient</a>
	</li>
	<li>
		<a href="{% url 'riget:home' %}">Excel export</a>
	</li>
{% endblock %}

{% block body %}
<div id="all">

	<input id="searchbox" placeholder="navn el.cpr" value="" type="text"/>
		
	<select id="select1" name="scanner">
		<option value="Scanner">Scanner</option>
		<option value="PET-1">PET-1</option> 
		<option value="PET-2">PET-2</option> 
		<option value="PET-3">PET-3</option> 
		<option value="PET-4">PET-4</option> 
		<option value="PET-5">PET-5</option> 
		<option value="PET-6">PET-6</option>
		<option value="PET-MR">PET-MR</option>
	</select>
	
	<select id="select2" name="scantype">
		<option value="Scantype">Scantype</option>
		<option value="Statisk">Statisk</option>
		<option value="Dynamisk">Dynamisk</option>
	</select>
	
	<select id="select3" name="tumortype">
		<option value="Tomur Type">Tomur tupe</option>
		<option value="GBM IV">GBM IV</option>
		<option value="HGG">HGG</option>
		<option value="AA III">AA III</option> 
		<option value="AA II/III">AA II/III</option> 
		<option value="AA II">AA II</option> 
		<option value="AA I/II">AA I/II</option> 
		<option value="AA I">AA I</option> 
		<option value="OD III">OD III</option>
		<option value="OD II/III">OD II/III</option>
		<option value="OD II">OD II</option> 
		<option value="OA III">OA III</option> 
		<option value="OA II/III">OA II/III</option> 
		<option value="OA II">OA II</option> 
		<option value="LGG">LGG</option> 
		<option value="Meningeom">Meningeom</option>
		<option value="Metastase">Metastase</option>
		<option value="Andet">Andet</option>	
	</select>

	<input id="age" name="age" type="text" placeholder="alder interval (f.eks. 1-19)" value=""/>
	
	<select id="select4" name="indikation">
		<option value="Indikation">Indikation</option>
		<option value="Primaeudregning">Primæreudregning</option>
		<option value="RT planlaegning">RT planlægning</option>
		<option value="Opfoelgning">Opfølgning</option>
		<option value="Projekt">Projekt</option>
		<option value="Andet">Andet</option>
	</select>
	
	<div id="table"></div>
</div>
<table class="usertable">
	<tbody>
		<td> Total nr formulars in search:</td>
		<td>{{ list_r }}</td>
		<td>Total nr patients in search:</td>
		<td>{{ list_p }}</td>
	</tbody>
</table>

<div id="users">
<table id="usertable" class="tablesorter">
	<thead>
		<tr>
			<th>CPR</a></th>
			<th>fornavn</a></th>
			<th>efternavn</a></th>
			<th>alder</a></th>
			<th>dato</a></th>
			<th>scanner</a></th>
			<th>tumor</a></th>
			<th>tmean/b</a></th>
			<th>tmax/b</a></th>
			<th>tumor vol.</a></th>
			<th>Projekt</a></th>
			<th>info</a></th>
			<th>interessante</a></th>
		</tr>
	</thead>
	<tbody class="list">
		{% for fet in fetlist%}
		<tr>
			<td class="CPR"><a href="{% url 'riget:fetview' CPR=fet.CPR %}">{{ fet.CPR }} </a></td>
			<td class="Name"><a href="{% url 'riget:fetview' CPR=fet.CPR %}">{{ fet.firstname }} </a></td>
			<td><a href="{% url 'riget:fetview' CPR=fet.CPR %}">{{ fet.lastname }} </a></td>
			<td><a href="{% url 'riget:fetview' CPR=fet.CPR %}">{{ fet.age }} </a></td>
			<td><a href="{% url 'riget:fetview' CPR=fet.CPR %}">{{ fet.scandato|date:"d-m-Y" }} </a></td>
			<td><a href="{% url 'riget:fetview' CPR=fet.CPR %}">{{ fet.scanner }} </a></td>
			<td><a href="{% url 'riget:fetview' CPR=fet.CPR %}">{{ fet.tumor_type }} </a></td>
			<td><a href="{% url 'riget:fetview' CPR=fet.CPR %}">{{ fet.roi_t_mean_b }} </a></td>
			<td><a href="{% url 'riget:fetview' CPR=fet.CPR %}">{{ fet.roi_t_max_b }} </a></td>
			<td><a href="{% url 'riget:fetview' CPR=fet.CPR %}">{{ fet.roi_tumor_vol }} </a></td>
			<td><a href="{% url 'riget:fetview' CPR=fet.CPR %}">{{ fet.indikation_projekt }} </a></td>
			<td><a href="{% url 'riget:fetview' CPR=fet.CPR %}">{{ fet.filter_t }} </a></td>
			<td><a href="{% url 'riget:fetview' CPR=fet.CPR %}">{{ fet.MR_DCE }} </a></td>
		</tr>
		{% endfor %}

	</tbody>
</table>
</div>
</div>

{%endblock%}

website/riget/templates/riget/fetpatient.html
{% extends 'riget/base.html' %}
{% load staticfiles %}

{% block title %}Home{% endblock %}

{% block menu%}
	<li>
		<a href="{% url 'riget:nyfetrecord' %}">Ny Record</a>
	</li>
	<li>		
		<a href="{% url 'riget:fet' %}">Oversigt</a>
	</li>
	<li>
		<a href="{% url 'riget:login' %}">Mine formulare</a>
	</li>
	<li>
		<a href="{% url 'riget:home' %}">Excel export</a>
	</li>

{% endblock %}

{% block body %}
<div class="" id="fetpatient">

<table id="usertable">
	<tr><td colspan="5" style="border-width:0px; height:20px; font-size:20px;">Patient</td></tr>
	<tr>
		<th>cpr</th>
		<th>navn</th>
		<th>FDG</th>
		<th>avastin</th>
		<th>Sidst ændret af</th>
	</tr>
	<tr>
		{% for p in person %}
		<td><a href="{% url 'riget:fetchang' CPR=p.CPR %}">{{ p.CPR }}</a></td>
		<td><a href="{% url 'riget:fetchang' CPR=p.CPR %}">{{ p.firstname }}  {{p.lastname}}</a></td>
		<td><a href="{% url 'riget:fetchang' CPR=p.CPR %}">{{ p.FDG }}</a></td>
		<td><a href="{% url 'riget:fetchang' CPR=p.CPR %}">{{ p.avastin }}</a></td>
		<td><a href="{% url 'riget:fetchang' CPR=p.CPR %}">{{ p.lasrChangedBy }}</a></td>
		{% endfor %}
	</tr>
</table>
<table id="usertable">
	<thead>
		<tr>
			<td colspan="5" style="border-width:0px; height:20px; font-size:20px;">Records</td>
		</tr>
		<tr>
			<td colspan="6" style="border-width:0px; color:#ffffff; background=#ffffff;"></th>
			<th><a href="">Graph</a></th>
			<th><a href="">Graph</a></th>
			<th><a href="">Graph</a></th>
			<td colspan="2" style="border-width:0px; color:#ffffff; background=#ffffff;"></th>
		</tr>
		<tr>
			<th>Dato</th>
			<th>Alder</th>
			<th>Scanner</th>
			<th>Scantype</th>
			<th>TumorType</th>
			<th>KurveForm</th>
			<th>Tmean/B</th>
			<th>TMax/B</th>
			<th>Tumor Vol. Krit. 1.6</th>
			<th>Projekt</th>
			<th>Interresant</th>
		</tr>
	</thead>
	<tbody>
		{% for r in records %}
		<tr>
		<td><a href="{% url 'riget:fet' %}">{{ r.scandato|date:"d-m-Y" }}</a></td>	
		<td><a href="{% url 'riget:fet' %}">{{ r.age }}</a></td>	
		<td><a href="{% url 'riget:fet' %}">{{ r.scanner }}</a></td>	
		<td><a href="{% url 'riget:fet' %}">{{ r.scantype_type }}</a></td>	
		<td><a href="{% url 'riget:fet' %}">{{ r.tumor_type }}</a></td>	
		<td><a href="{% url 'riget:fet' %}">{{ r.kurveform }}</a></td>	
		<td><a href="{% url 'riget:fet' %}">{{ r.roi_t_mean_b }}</a></td>	
		<td><a href="{% url 'riget:fet' %}">{{ r.roi_t_max_b }}</a></td>	
		<td><a href="{% url 'riget:fet' %}">{{ r.roi_tumor_vol }}</a></td>	
		<td><a href="{% url 'riget:fet' %}">{{ r.indikation_projekt }}</a></td>	
		<td><a href="{% url 'riget:fet' %}">{{ r.interessant_case }}</a></td>	
		</tr>
		{% endfor %}

	
	</tbody>

</table>


</div>


{%endblock%}

website/riget/templates/riget/home.html
{% extends 'riget/base.html' %}
{% load staticfiles %}

{% block title %}Home{% endblock %}

{% block menu%}
	<a class="w3-bar-item w3-button" href="{% url 'riget:login' %}">LS</a>
	<a class="w3-bar-item w3-button" href="{% url 'riget:pib' %}">PiB</a>
	<a class="w3-bar-item w3-button" href="{% url 'riget:fet' %}">FET</a>
	<a class="w3-bar-item w3-button" href="{% url 'riget:login' %}">Admin</a>
{% endblock %}

{% block body %}
<div id="main_menu">
	
	<table id="forsideTable" cellspacing="10">
	<tbody>
		<tr>
			<td style="background-color: #476D9B">
				<a href="{% url 'riget:home' %}">Learning system</a>
			</td>
		</tr>
		
		<tr>
			<td style="background-color: #B8D3EF">
				<a href="{% url 'riget:pib' %}">PiB</a>
			</td>
		</tr>
		<tr>
			<td style="background-color: #95BAEC">
				<a href="{% url 'riget:fet' %}">FET</a>
			</td>
		</tr>
		<tr>
			<td style="background-color: #55BAEC">
				<a href="{% url 'riget:home' %}">Adminstrate user</a>
			</td>
		</tr>
	</tbody>
	</table>
</div>

{%endblock%}

website/riget/templates/riget/nyfetperson.html
{% extends 'riget/base.html' %}
{% load staticfiles %}

{% block title %}Ny Fet Record{% endblock %}

{% block menu%}
	<li>
		<a href="{% url 'riget:nyfetrecord' %}">Ny Record</a>
	</li>
	<li>
		<a href="{% url 'riget:fet' %}">Oversigt</a>
	</li>
	<li>
		<a href="{% url 'riget:nyfetperson' %}">Ny Patient</a>
	</li>
	<li>
		<a href="{% url 'riget:login' %}">Excel export</a>
	</li>
{% endblock %}

{% block body %}
	<div class="messageFET">
		{% if done %}
			<h3>{{ done }}</h3>
		{% endif %}
	</div>

	<form action="." method="POST" class="inputformFET">
	{% csrf_token %}
		<input name="submitted" value="TRUE" type="hidden"/>
		<table>
			<tbody>
				<tr>
					<td>CPR</td>
					<td><input name="CPR" type="text"/></td>
				</tr>
				<tr>
					<td>Navn</td>
					<td><input name="firstname" type="text"/></td>
					<td><input name="lastname" type="text"/></td>
				</tr>
				<tr>
					<td>FDG</td>
					<input name="FDG" value="False" type="hidden"/>
					<td><input id="x1" name="FDG" value="True" td="" type="checkbox"/></td>
				</tr>
				<tr>
					<td>AVASTIN</td>
					<input name="avastin" value="False" type="hidden"/>
					<td><input id="x1" name="avastin" value="True" td="" type="checkbox"/></td>
				</tr>
				<tr>
					<td><style="border-width : 0px;"> </td>
					<td colspan="1" style="border-width : 0px;">
						<input style="float:left; width:50%;" onclick="opdateAlert()" value="Opret" type="submit"/>
					</td>
				</tr>
			</tbody>
		</table>

	</form>

{%endblock%}

website/riget/templates/riget/nyfetpersonchange.html
{% extends 'riget/base.html' %}
{% load staticfiles %}

{% block title %}Ny Fet Record{% endblock %}

{% block menu%}
	<li>
		<a href="{% url 'riget:nyfetrecord' %}">Ny Record</a>
	</li>
	<li>
		<a href="{% url 'riget:fet' %}">Oversigt</a>
	</li>
	<li>
		<a href="{% url 'riget:nyfetperson' %}">Ny Patient</a>
	</li>
	<li>
		<a href="{% url 'riget:login' %}">Excel export</a>
	</li>
{% endblock %}

{% block body %}
	<div class="messageFET">
		{% if done %}
			<h3>{{ done }}</h3>
		{% endif %}
	</div>
	
	{% for p in person %}
	<form action="." method="POST" class="inputformFET">
	{% csrf_token %}
		<input name="submitted" value="TRUE" type="hidden"/>
		<table>
			<tbody>
				<tr>
					<td>CPR</td>
					<td><input name="CPR" type="text" value="{{ p.CPR }}"/></td>
				</tr>
				<tr>
					<td>Navn</td>
					<td><input name="firstname" type="text" value="{{ p.firstname }}"/></td>
					<td><input name="lastname" type="text" value="{{ p.lastname }}"/></td>
				</tr>
				<tr>
					<td>FDG</td>
					<input name="FDG" value="False" type="hidden"/>
					<td><input id="x1" name="FDG" value="True" td="" type="checkbox" {% if p.FDG %}checked {% endif %}/></td>
				</tr>
				<tr>
					<td>AVASTIN</td>
					<input name="avastin" value="False" type="hidden"/>
					<td><input id="x1" name="avastin" value="True" td="" type="checkbox" {% if p.avastin%}checked{% endif %}/></td>
				</tr>
				<tr>
					<td><style="border-width : 0px;"> </td>
					<td colspan="1" style="border-width : 0px;">
						<input style="float:left; width:50%;" onclick="opdateAlert()" value="Opret" type="submit"/>
					</td>
				</tr>
			</tbody>
		</table>

	</form>
	{% endfor %}

{%endblock%}